#Propeties Of upload images
upload:
  vehicle-images:
    directory: ${VEHICLE_UPLOAD_DIRECTORY:static-upload/vehicle-images}
    allowed-extensions: .png, .jpg, .jpeg
    max-file-size: 5MB

  pieces-images:
    directory: ${PIECE_UPLOAD_DIRECTORY:static-upload/pieces-images}
    allowed-extensions: .png, .jpg, .jpeg
    max-file-size: 5MB

static-upload:
  upload-directory: ${STATIC_CONTENT_UPLOAD_DIRECTORY:static-upload}
  url: ${STATIC_CONTENT_PATH:/images/**}

token:
  signing:
    key: ${TOKEN_SIGNING_KEY:412F4428472B4B6250655368566E5970337336763979244226452948404D6352}

spring:

  # Data Base configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meddichetruck}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  sql:
    init:
      mode: always
      schema-locations: classpath:create_security_schema.sql

  # Jakarta persistence configuration
  jpa:
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true

    show-sql: false

    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

  liquibase:
    changelog: changelog/app-changelog.xml
    default-schema: meddichetruck
    enabled: false

  servlet:
    multipart:
      enabled: true

