#Propeties Of FileStorageService
default:
  resource:
    path: mt-main/src/main/resources/static/images

  extension: .png

token:
  signing:
    key: ${TOKEN_SIGNING_KEY:412F4428472B4B6250655368566E5970337336763979244226452948404D6352}

spring:

  # Data Base configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/meddichetruck}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}

  sql:
    init:
      mode: always
      schema-locations: classpath:create_security_schema.sql

  # Jakarta persistence configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show-sql: false

    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

  liquibase:
    changelog: changelog/app-changelog.xml
    default-schema: meddichetruck
    enabled: false




