version: '3.8'

services:
  db:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=meddichetruck
    ports:
      - "5432:5432"

  app-back:
    image: 'meddichetruckback:latest'
    build:
      context: .
    container_name: application-backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/meddichetruck
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"

  app-front:
    image: 'meddichetruckfront:latest'
    build:
      context: .
    container_name: application-frontend
    depends_on:
      - app-back
    environment:
        - DOMAIN=http://localhost:8080,
        - API_VERSION=/api/v1,

    ports:
      - "4200:4200"

