
spring:

  # Data Base configuration
  datasource:
    url: jdbc:mysql://localhost:3306/meddichetruck?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Jakarta persistence configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

    show-sql: true

    hibernate:
      ddl-auto: create

  liquibase:
    changelog: db/changelog/app-changelog.xml
    default-schema: meddichetruck


